/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUIConcesionario.*;
import java.io.IOException;
import javax.swing.JOptionPane;
import persistencia.ArchivoMotocicletas;
import persistencia.Archivoconsesionario;


/**
 *
 * @author Admin
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        menuBar5 = new java.awt.MenuBar();
        menu9 = new java.awt.Menu();
        menu10 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        lblAdicionarConcesionario = new javax.swing.JMenuItem();
        lblBuscar1 = new javax.swing.JMenuItem();
        lblActualizar1 = new javax.swing.JMenuItem();
        lblEliminar1 = new javax.swing.JMenuItem();
        lblListar1 = new javax.swing.JMenuItem();
        lblPresupuestoTotal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        lblAdicionar = new javax.swing.JMenuItem();
        lblBuscar = new javax.swing.JMenuItem();
        lblActualizar = new javax.swing.JMenuItem();
        lblEliminar = new javax.swing.JMenuItem();
        lblListar = new javax.swing.JMenuItem();
        lblPrecioTotal = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        menu9.setLabel("File");
        menuBar5.add(menu9);

        menu10.setLabel("Edit");
        menuBar5.add(menu10);

        jLabel1.setText("jLabel1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu6.setText("Concesionario");

        lblAdicionarConcesionario.setText("Adicionar");
        lblAdicionarConcesionario.addActionListener(this::lblAdicionarConcesionarioActionPerformed);
        jMenu6.add(lblAdicionarConcesionario);

        lblBuscar1.setText("Buscar");
        lblBuscar1.addActionListener(this::lblBuscar1ActionPerformed);
        jMenu6.add(lblBuscar1);

        lblActualizar1.setText("Actualizar");
        lblActualizar1.addActionListener(this::lblActualizar1ActionPerformed);
        jMenu6.add(lblActualizar1);

        lblEliminar1.setText("Eliminar");
        lblEliminar1.addActionListener(this::lblEliminar1ActionPerformed);
        jMenu6.add(lblEliminar1);

        lblListar1.setText("Listar");
        lblListar1.addActionListener(this::lblListar1ActionPerformed);
        jMenu6.add(lblListar1);

        lblPresupuestoTotal.setText("Presupuesto Total");
        lblPresupuestoTotal.addActionListener(this::lblPresupuestoTotalActionPerformed);
        jMenu6.add(lblPresupuestoTotal);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Motos");

        lblAdicionar.setText("Adicionar");
        lblAdicionar.addActionListener(this::lblAdicionarActionPerformed);
        jMenu2.add(lblAdicionar);

        lblBuscar.setText("Buscar");
        lblBuscar.addActionListener(this::lblBuscarActionPerformed);
        jMenu2.add(lblBuscar);

        lblActualizar.setText("Actualizar");
        lblActualizar.addActionListener(this::lblActualizarActionPerformed);
        jMenu2.add(lblActualizar);

        lblEliminar.setText("Eliminar");
        lblEliminar.addActionListener(this::lblEliminarActionPerformed);
        jMenu2.add(lblEliminar);

        lblListar.setText("Listar");
        lblListar.addActionListener(this::lblListarActionPerformed);
        jMenu2.add(lblListar);

        lblPrecioTotal.setText("PrecioTotal");
        lblPrecioTotal.addActionListener(this::lblPrecioTotalActionPerformed);
        jMenu2.add(lblPrecioTotal);

        jMenuBar1.add(jMenu2);

        Ayuda.setText("Ayuda");

        jMenuItem2.setText("Acerca de.....");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        Ayuda.add(jMenuItem2);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAdicionarActionPerformed

        GUIAdicionarMoto ventana = new GUIAdicionarMoto();
        ventana.setLocationRelativeTo(this);

        ventana.setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );
        ventana.setVisible(true);

    }//GEN-LAST:event_lblAdicionarActionPerformed

    private void lblBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBuscarActionPerformed

        GUIBuscarMoto ventana = new GUIBuscarMoto();

        ventana.setLocationRelativeTo(this);

        ventana.setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );
        ventana.setVisible(true);
    }//GEN-LAST:event_lblBuscarActionPerformed

    private void lblActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblActualizarActionPerformed
        GUIActualizarMoto ventana = new GUIActualizarMoto();

        ventana.setLocationRelativeTo(this);

        ventana.setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        ventana.setVisible(true);

        System.out.println("6. VENTANA VISIBLE");
    }//GEN-LAST:event_lblActualizarActionPerformed

    private void lblEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEliminarActionPerformed
        GUIEliminarMoto ventana = new GUIEliminarMoto();

        ventana.setLocationRelativeTo(this);

        ventana.setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );
        ventana.setVisible(true);
    }//GEN-LAST:event_lblEliminarActionPerformed

    private void lblListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblListarActionPerformed
        GUIListarMoto ventana = new GUIListarMoto();

        ventana.setLocationRelativeTo(this);

        ventana.setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );
        ventana.setVisible(true);
    }//GEN-LAST:event_lblListarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        GUIAyuda ventana = new GUIAyuda();
        ventana.setLocationRelativeTo(this);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void lblAdicionarConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAdicionarConcesionarioActionPerformed

        GUIAdicionarConcesionario ventana = new GUIAdicionarConcesionario();
        ventana.setLocationRelativeTo(this);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);


    }//GEN-LAST:event_lblAdicionarConcesionarioActionPerformed

    private void lblBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBuscar1ActionPerformed

        GUIBuscarConcesionario ventana = new GUIBuscarConcesionario();
        ventana.setLocationRelativeTo(this);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

    }//GEN-LAST:event_lblBuscar1ActionPerformed

    private void lblActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblActualizar1ActionPerformed

        GUIActualizarConcesionario ventana = new GUIActualizarConcesionario();
        ventana.setLocationRelativeTo(this);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);

    }//GEN-LAST:event_lblActualizar1ActionPerformed

    private void lblEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblEliminar1ActionPerformed

        GUIEliminarConcesionario ventana = new GUIEliminarConcesionario();
        ventana.setLocationRelativeTo(this);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_lblEliminar1ActionPerformed

    private void lblListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblListar1ActionPerformed

        GUIListarConcesionario ventana = new GUIListarConcesionario();
        ventana.setLocationRelativeTo(this);
        ventana.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_lblListar1ActionPerformed

    private void lblPresupuestoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPresupuestoTotalActionPerformed
        try {
            Archivoconsesionario archivo = new Archivoconsesionario();
            
            double sumaPre = archivo.calcularPresupuesto();

            

            JOptionPane.showMessageDialog(
                    this,
                    "La sumatoria de los precios es: $" + sumaPre,
                    "Sumatoria",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_lblPresupuestoTotalActionPerformed

    private void lblPrecioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPrecioTotalActionPerformed
        try {

            ArchivoMotocicletas archivo = new ArchivoMotocicletas();

            double suma = archivo.calcularPrecios();

            JOptionPane.showMessageDialog(
                    this,
                    "La sumatoria de los precios es: $" + suma,
                    "Sumatoria",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_lblPrecioTotalActionPerformed

    /**
     * S
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem lblActualizar;
    private javax.swing.JMenuItem lblActualizar1;
    private javax.swing.JMenuItem lblAdicionar;
    private javax.swing.JMenuItem lblAdicionarConcesionario;
    private javax.swing.JMenuItem lblBuscar;
    private javax.swing.JMenuItem lblBuscar1;
    private javax.swing.JMenuItem lblEliminar;
    private javax.swing.JMenuItem lblEliminar1;
    private javax.swing.JMenuItem lblListar;
    private javax.swing.JMenuItem lblListar1;
    private javax.swing.JMenuItem lblPrecioTotal;
    private javax.swing.JMenuItem lblPresupuestoTotal;
    private java.awt.Menu menu1;
    private java.awt.Menu menu10;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.Menu menu9;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    private java.awt.MenuBar menuBar5;
    // End of variables declaration//GEN-END:variables
}
